language: csharp
solution: WirelessConfigurationChanger.sln
install:
  - nuget restore WirelessConfigurationChanger.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release WirelessConfigurationChanger.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./UnitTestProject/bin/Release/UnitTestProject.dll
