language: csharp
solution: WirelessConfigurationChanger.sln
install:
  - nuget restore WirelessConfigurationChanger.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release WirelessConfigurationChanger.sln
